### ISSUE TITLE
BERd devices

### ISSUE THREAD

**Issue by DalvinderSingh** [Samyoul/The-ultimate-repair-system-issues#104] opened 2017-03-12 20:00 UTC
I don't think a device can be collected once a device BERd, Once it is BERd it should go to the collection Page. Where it can be collected or go in to stock (I'm aware this is a future development)

**Comment by Samyoul** [comment] 2017-03-12 22:00
Duplicate of https://github.com/Samyoul/The-ultimate-repair-system-issues/issues/47

**Closed by Samyoul** 2017-03-12 22:00 UTC
